### ISSUE TITLE
Using Story utility.

### ISSUE THREAD

**Issue by appuCoding** [isha112/webdev#3]
Use story utility to navigate to the experiments.

**Comment by isha112** [comment]
Hello Sneha,

I have done 5th exp of week3 as well as have added to code description of week3. So I request you to check it out and close the issues. For week4 I was not able to the 5th exp because of Algo assignment. I will finish it today and upload it. 
For the next week are we supposed to continue with 5 exp or 3 exp per week?
And also suggest me if I need to improve somewhere.

Thank you,
Isha Shah

----- Original Message -----

**Comment by appuCoding** [comment]
## You can close the issues

Sent from my mobile via Mail.Ru
Monday, 16 February 2015, 06:59PM -05:00 from isha112 notifications@github.com:
Hello Sneha,
I have done 5th exp of week3 as well as have added to code description of week3. So I request you to check it out and close the issues. For week4 I was not able to the 5th exp because of Algo assignment. I will finish it today and upload it.
For the next week are we supposed to continue with 5 exp or 3 exp per week?
And also suggest me if I need to improve somewhere.
Thank you,
Isha Shah
----- Original Message -----
